// THIS FILE IS AUTOGENERATED. DO NOT CHANGE ANYTHING.

command_trie.insert({ "pushr", 5 }, 0);
command_trie.insert({ "popr", 4 }, 1);
command_trie.insert({ "add", 3 }, 2);
command_trie.insert({ "out", 3 }, 3);
command_trie.insert({ "in", 2 }, 4);
command_trie.insert({ "push", 4 }, 5);
command_trie.insert({ "pop", 3 }, 6);
command_trie.insert({ "jmp", 3 }, 7);
command_trie.insert({ "end", 3 }, 8);
command_trie.insert({ "cmp", 3 }, 9);
command_trie.insert({ "je", 2 }, 10);
command_trie.insert({ "jb", 2 }, 11);
command_trie.insert({ "call", 4 }, 12);
command_trie.insert({ "ret", 3 }, 13);
command_trie.insert({ "mul", 3 }, 14);
command_trie.insert({ "sub", 3 }, 15);
command_trie.insert({ "ja", 2 }, 16);
command_trie.insert({ "jae", 3 }, 17);
command_trie.insert({ "jbe", 3 }, 18);
command_trie.insert({ "jne", 3 }, 19);
command_trie.insert({ "sqrt", 4 }, 20);
command_trie.insert({ "sqr", 3 }, 21);
command_trie.insert({ "div", 3 }, 22);
command_trie.insert({ "less", 4 }, 23);
command_trie.insert({ "equal", 5 }, 24);
command_trie.insert({ "cmptop", 6 }, 25);
