// THIS FILE IS AUTOGENERATED. DO NOT CHANGE ANYTHING.

case 0: {
	pushr();
	break;
}
case 1: {
	popr();
	break;
}
case 2: {
	add();
	break;
}
case 3: {
	out();
	break;
}
case 4: {
	in();
	break;
}
case 5: {
	push();
	break;
}
case 6: {
	pop();
	break;
}
case 7: {
	jmp();
	break;
}
case 8: {
	end();
	break;
}
case 9: {
	cmp();
	break;
}
case 10: {
	je();
	break;
}
case 11: {
	jb();
	break;
}
case 12: {
	call();
	break;
}
case 13: {
	ret();
	break;
}
case 14: {
	mul();
	break;
}
case 15: {
	sub();
	break;
}
case 16: {
	ja();
	break;
}
case 17: {
	jae();
	break;
}
case 18: {
	jbe();
	break;
}
case 19: {
	jne();
	break;
}
case 20: {
	sqrt();
	break;
}
case 21: {
	sqr();
	break;
}
case 22: {
	div();
	break;
}
case 23: {
	less();
	break;
}
case 24: {
	equal();
	break;
}
case 25: {
	cmptop();
	break;
}
